-- Inserção de dados ampliada e sem repetição na tabela 'countries'

INSERT INTO countries (region, key_word, name, population) VALUES ('América do Norte', 3, 'País 1 América do Norte', 548959);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Norte', 3, 'País 2 América do Norte', 518781);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Norte', 3, 'País 3 América do Norte', 743395);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Norte', 3, 'País 4 América do Norte', 269292);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Norte', 1, 'País 5 América do Norte', 395909);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Norte', 3, 'País 6 América do Norte', 508599);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Norte', 1, 'País 7 América do Norte', 755994);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Norte', 3, 'País 8 América do Norte', 394192);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Norte', 1, 'País 9 América do Norte', 530007);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Norte', 3, 'País 10 América do Norte', 410540);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Norte', 3, 'País 11 América do Norte', 880039);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Norte', 1, 'País 12 América do Norte', 293677);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Norte', 1, 'País 13 América do Norte', 343669);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Norte', 3, 'País 14 América do Norte', 657190);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Norte', 1, 'País 15 América do Norte', 774019);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Norte', 3, 'País 16 América do Norte', 181327);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Norte', 2, 'País 17 América do Norte', 885161);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Norte', 1, 'País 18 América do Norte', 615357);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Norte', 2, 'País 19 América do Norte', 927586);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Norte', 3, 'País 20 América do Norte', 239897);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Norte', 1, 'País 21 América do Norte', 656195);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Norte', 3, 'País 22 América do Norte', 739999);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Norte', 1, 'País 23 América do Norte', 997397);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Norte', 2, 'País 24 América do Norte', 862760);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Norte', 3, 'País 25 América do Norte', 306814);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Norte', 3, 'País 26 América do Norte', 196394);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Norte', 1, 'País 27 América do Norte', 650282);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Norte', 2, 'País 28 América do Norte', 330554);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Norte', 3, 'País 29 América do Norte', 935067);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Norte', 2, 'País 30 América do Norte', 876250);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Norte', 3, 'País 31 América do Norte', 106060);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Norte', 3, 'País 32 América do Norte', 155330);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Norte', 1, 'País 33 América do Norte', 229573);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Norte', 1, 'País 34 América do Norte', 428646);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Norte', 1, 'País 35 América do Norte', 661958);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Norte', 1, 'País 36 América do Norte', 570063);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Norte', 1, 'País 37 América do Norte', 141079);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Norte', 1, 'País 38 América do Norte', 519108);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Norte', 1, 'País 39 América do Norte', 289740);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Norte', 3, 'País 40 América do Norte', 440140);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Norte', 1, 'País 41 América do Norte', 975985);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Norte', 2, 'País 42 América do Norte', 241454);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Norte', 2, 'País 43 América do Norte', 721182);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Norte', 1, 'País 44 América do Norte', 892027);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Norte', 1, 'País 45 América do Norte', 266718);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Norte', 3, 'País 46 América do Norte', 130238);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Norte', 3, 'País 47 América do Norte', 441053);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Norte', 2, 'País 48 América do Norte', 217784);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Norte', 1, 'País 49 América do Norte', 512917);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Norte', 1, 'País 50 América do Norte', 659554);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Norte', 3, 'País 51 América do Norte', 134653);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Norte', 3, 'País 52 América do Norte', 223900);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Norte', 3, 'País 53 América do Norte', 702813);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Norte', 2, 'País 54 América do Norte', 964546);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Norte', 2, 'País 55 América do Norte', 357133);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Norte', 3, 'País 56 América do Norte', 967918);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Norte', 1, 'País 57 América do Norte', 602807);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Norte', 2, 'País 58 América do Norte', 224453);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Norte', 3, 'País 59 América do Norte', 397797);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Norte', 1, 'País 60 América do Norte', 915254);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Norte', 3, 'País 61 América do Norte', 984341);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Norte', 2, 'País 62 América do Norte', 594637);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Norte', 1, 'País 63 América do Norte', 591032);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Norte', 1, 'País 64 América do Norte', 904323);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Norte', 2, 'País 65 América do Norte', 626799);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Norte', 2, 'País 66 América do Norte', 862453);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Norte', 3, 'País 67 América do Norte', 460734);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Norte', 2, 'País 68 América do Norte', 938484);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Norte', 2, 'País 69 América do Norte', 623518);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Norte', 1, 'País 70 América do Norte', 847167);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Norte', 3, 'País 71 América do Norte', 616971);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Norte', 1, 'País 72 América do Norte', 700132);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Norte', 3, 'País 73 América do Norte', 342419);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Norte', 2, 'País 74 América do Norte', 370211);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Norte', 2, 'País 75 América do Norte', 986722);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Norte', 3, 'País 76 América do Norte', 670273);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Norte', 1, 'País 77 América do Norte', 477945);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Norte', 1, 'País 78 América do Norte', 346491);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Norte', 2, 'País 79 América do Norte', 289183);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Norte', 3, 'País 80 América do Norte', 625716);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Norte', 3, 'País 81 América do Norte', 852885);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Norte', 3, 'País 82 América do Norte', 519342);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Norte', 3, 'País 83 América do Norte', 244932);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Norte', 3, 'País 84 América do Norte', 338145);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Norte', 2, 'País 85 América do Norte', 177434);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Norte', 1, 'País 86 América do Norte', 347479);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Norte', 3, 'País 87 América do Norte', 472763);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Norte', 3, 'País 88 América do Norte', 121032);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Norte', 1, 'País 89 América do Norte', 186674);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Norte', 2, 'País 90 América do Norte', 585616);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Norte', 2, 'País 91 América do Norte', 174596);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Norte', 2, 'País 92 América do Norte', 182438);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Norte', 3, 'País 93 América do Norte', 102593);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Norte', 1, 'País 94 América do Norte', 870856);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Norte', 3, 'País 95 América do Norte', 710766);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Norte', 1, 'País 96 América do Norte', 997376);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Norte', 3, 'País 97 América do Norte', 714095);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Norte', 2, 'País 98 América do Norte', 484277);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Norte', 1, 'País 99 América do Norte', 110425);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Norte', 1, 'País 100 América do Norte', 340563);
INSERT INTO countries (region, key_word, name, population) VALUES ('Europa Ocidental', 3, 'País 1 Europa Ocidental', 576709);
INSERT INTO countries (region, key_word, name, population) VALUES ('Europa Ocidental', 3, 'País 2 Europa Ocidental', 183437);
INSERT INTO countries (region, key_word, name, population) VALUES ('Europa Ocidental', 1, 'País 3 Europa Ocidental', 414971);
INSERT INTO countries (region, key_word, name, population) VALUES ('Europa Ocidental', 3, 'País 4 Europa Ocidental', 238249);
INSERT INTO countries (region, key_word, name, population) VALUES ('Europa Ocidental', 2, 'País 5 Europa Ocidental', 937047);
INSERT INTO countries (region, key_word, name, population) VALUES ('Europa Ocidental', 1, 'País 6 Europa Ocidental', 649938);
INSERT INTO countries (region, key_word, name, population) VALUES ('Europa Ocidental', 3, 'País 7 Europa Ocidental', 168861);
INSERT INTO countries (region, key_word, name, population) VALUES ('Europa Ocidental', 3, 'País 8 Europa Ocidental', 371993);
INSERT INTO countries (region, key_word, name, population) VALUES ('Europa Ocidental', 1, 'País 9 Europa Ocidental', 312427);
INSERT INTO countries (region, key_word, name, population) VALUES ('Europa Ocidental', 1, 'País 10 Europa Ocidental', 163129);
INSERT INTO countries (region, key_word, name, population) VALUES ('Europa Ocidental', 1, 'País 11 Europa Ocidental', 645788);
INSERT INTO countries (region, key_word, name, population) VALUES ('Europa Ocidental', 1, 'País 12 Europa Ocidental', 572203);
INSERT INTO countries (region, key_word, name, population) VALUES ('Europa Ocidental', 3, 'País 13 Europa Ocidental', 607228);
INSERT INTO countries (region, key_word, name, population) VALUES ('Europa Ocidental', 2, 'País 14 Europa Ocidental', 672710);
INSERT INTO countries (region, key_word, name, population) VALUES ('Europa Ocidental', 3, 'País 15 Europa Ocidental', 506111);
INSERT INTO countries (region, key_word, name, population) VALUES ('Europa Ocidental', 3, 'País 16 Europa Ocidental', 610617);
INSERT INTO countries (region, key_word, name, population) VALUES ('Europa Ocidental', 2, 'País 17 Europa Ocidental', 597954);
INSERT INTO countries (region, key_word, name, population) VALUES ('Europa Ocidental', 1, 'País 18 Europa Ocidental', 485141);
INSERT INTO countries (region, key_word, name, population) VALUES ('Europa Ocidental', 2, 'País 19 Europa Ocidental', 288720);
INSERT INTO countries (region, key_word, name, population) VALUES ('Europa Ocidental', 3, 'País 20 Europa Ocidental', 805890);
INSERT INTO countries (region, key_word, name, population) VALUES ('Europa Ocidental', 3, 'País 21 Europa Ocidental', 265539);
INSERT INTO countries (region, key_word, name, population) VALUES ('Europa Ocidental', 1, 'País 22 Europa Ocidental', 514520);
INSERT INTO countries (region, key_word, name, population) VALUES ('Europa Ocidental', 3, 'País 23 Europa Ocidental', 120658);
INSERT INTO countries (region, key_word, name, population) VALUES ('Europa Ocidental', 3, 'País 24 Europa Ocidental', 170737);
INSERT INTO countries (region, key_word, name, population) VALUES ('Europa Ocidental', 3, 'País 25 Europa Ocidental', 553141);
INSERT INTO countries (region, key_word, name, population) VALUES ('Europa Ocidental', 1, 'País 26 Europa Ocidental', 230972);
INSERT INTO countries (region, key_word, name, population) VALUES ('Europa Ocidental', 2, 'País 27 Europa Ocidental', 790965);
INSERT INTO countries (region, key_word, name, population) VALUES ('Europa Ocidental', 1, 'País 28 Europa Ocidental', 666743);
INSERT INTO countries (region, key_word, name, population) VALUES ('Europa Ocidental', 2, 'País 29 Europa Ocidental', 239805);
INSERT INTO countries (region, key_word, name, population) VALUES ('Europa Ocidental', 1, 'País 30 Europa Ocidental', 921895);
INSERT INTO countries (region, key_word, name, population) VALUES ('Europa Ocidental', 3, 'País 31 Europa Ocidental', 817042);
INSERT INTO countries (region, key_word, name, population) VALUES ('Europa Ocidental', 2, 'País 32 Europa Ocidental', 179386);
INSERT INTO countries (region, key_word, name, population) VALUES ('Europa Ocidental', 1, 'País 33 Europa Ocidental', 924484);
INSERT INTO countries (region, key_word, name, population) VALUES ('Europa Ocidental', 3, 'País 34 Europa Ocidental', 697341);
INSERT INTO countries (region, key_word, name, population) VALUES ('Europa Ocidental', 2, 'País 35 Europa Ocidental', 528976);
INSERT INTO countries (region, key_word, name, population) VALUES ('Europa Ocidental', 3, 'País 36 Europa Ocidental', 365056);
INSERT INTO countries (region, key_word, name, population) VALUES ('Europa Ocidental', 1, 'País 37 Europa Ocidental', 954452);
INSERT INTO countries (region, key_word, name, population) VALUES ('Europa Ocidental', 3, 'País 38 Europa Ocidental', 607255);
INSERT INTO countries (region, key_word, name, population) VALUES ('Europa Ocidental', 3, 'País 39 Europa Ocidental', 461047);
INSERT INTO countries (region, key_word, name, population) VALUES ('Europa Ocidental', 2, 'País 40 Europa Ocidental', 242662);
INSERT INTO countries (region, key_word, name, population) VALUES ('Europa Ocidental', 3, 'País 41 Europa Ocidental', 945806);
INSERT INTO countries (region, key_word, name, population) VALUES ('Europa Ocidental', 2, 'País 42 Europa Ocidental', 715475);
INSERT INTO countries (region, key_word, name, population) VALUES ('Europa Ocidental', 1, 'País 43 Europa Ocidental', 726506);
INSERT INTO countries (region, key_word, name, population) VALUES ('Europa Ocidental', 3, 'País 44 Europa Ocidental', 366267);
INSERT INTO countries (region, key_word, name, population) VALUES ('Europa Ocidental', 2, 'País 45 Europa Ocidental', 252600);
INSERT INTO countries (region, key_word, name, population) VALUES ('Europa Ocidental', 1, 'País 46 Europa Ocidental', 627457);
INSERT INTO countries (region, key_word, name, population) VALUES ('Europa Ocidental', 3, 'País 47 Europa Ocidental', 974076);
INSERT INTO countries (region, key_word, name, population) VALUES ('Europa Ocidental', 2, 'País 48 Europa Ocidental', 867246);
INSERT INTO countries (region, key_word, name, population) VALUES ('Europa Ocidental', 1, 'País 49 Europa Ocidental', 263011);
INSERT INTO countries (region, key_word, name, population) VALUES ('Europa Ocidental', 3, 'País 50 Europa Ocidental', 657402);
INSERT INTO countries (region, key_word, name, population) VALUES ('Europa Ocidental', 2, 'País 51 Europa Ocidental', 185834);
INSERT INTO countries (region, key_word, name, population) VALUES ('Europa Ocidental', 1, 'País 52 Europa Ocidental', 833993);
INSERT INTO countries (region, key_word, name, population) VALUES ('Europa Ocidental', 2, 'País 53 Europa Ocidental', 647861);
INSERT INTO countries (region, key_word, name, population) VALUES ('Europa Ocidental', 1, 'País 54 Europa Ocidental', 725623);
INSERT INTO countries (region, key_word, name, population) VALUES ('Europa Ocidental', 3, 'País 55 Europa Ocidental', 633570);
INSERT INTO countries (region, key_word, name, population) VALUES ('Europa Ocidental', 3, 'País 56 Europa Ocidental', 745448);
INSERT INTO countries (region, key_word, name, population) VALUES ('Europa Ocidental', 1, 'País 57 Europa Ocidental', 912615);
INSERT INTO countries (region, key_word, name, population) VALUES ('Europa Ocidental', 3, 'País 58 Europa Ocidental', 955674);
INSERT INTO countries (region, key_word, name, population) VALUES ('Europa Ocidental', 1, 'País 59 Europa Ocidental', 969847);
INSERT INTO countries (region, key_word, name, population) VALUES ('Europa Ocidental', 3, 'País 60 Europa Ocidental', 196056);
INSERT INTO countries (region, key_word, name, population) VALUES ('Europa Ocidental', 2, 'País 61 Europa Ocidental', 913384);
INSERT INTO countries (region, key_word, name, population) VALUES ('Europa Ocidental', 1, 'País 62 Europa Ocidental', 449443);
INSERT INTO countries (region, key_word, name, population) VALUES ('Europa Ocidental', 2, 'País 63 Europa Ocidental', 481272);
INSERT INTO countries (region, key_word, name, population) VALUES ('Europa Ocidental', 2, 'País 64 Europa Ocidental', 439966);
INSERT INTO countries (region, key_word, name, population) VALUES ('Europa Ocidental', 3, 'País 65 Europa Ocidental', 720279);
INSERT INTO countries (region, key_word, name, population) VALUES ('Europa Ocidental', 3, 'País 66 Europa Ocidental', 233982);
INSERT INTO countries (region, key_word, name, population) VALUES ('Europa Ocidental', 1, 'País 67 Europa Ocidental', 994255);
INSERT INTO countries (region, key_word, name, population) VALUES ('Europa Ocidental', 2, 'País 68 Europa Ocidental', 378244);
INSERT INTO countries (region, key_word, name, population) VALUES ('Europa Ocidental', 3, 'País 69 Europa Ocidental', 435792);
INSERT INTO countries (region, key_word, name, population) VALUES ('Europa Ocidental', 3, 'País 70 Europa Ocidental', 665377);
INSERT INTO countries (region, key_word, name, population) VALUES ('Europa Ocidental', 1, 'País 71 Europa Ocidental', 202150);
INSERT INTO countries (region, key_word, name, population) VALUES ('Europa Ocidental', 2, 'País 72 Europa Ocidental', 431769);
INSERT INTO countries (region, key_word, name, population) VALUES ('Europa Ocidental', 2, 'País 73 Europa Ocidental', 736164);
INSERT INTO countries (region, key_word, name, population) VALUES ('Europa Ocidental', 1, 'País 74 Europa Ocidental', 807084);
INSERT INTO countries (region, key_word, name, population) VALUES ('Europa Ocidental', 3, 'País 75 Europa Ocidental', 650201);
INSERT INTO countries (region, key_word, name, population) VALUES ('Europa Ocidental', 1, 'País 76 Europa Ocidental', 743634);
INSERT INTO countries (region, key_word, name, population) VALUES ('Europa Ocidental', 3, 'País 77 Europa Ocidental', 120813);
INSERT INTO countries (region, key_word, name, population) VALUES ('Europa Ocidental', 2, 'País 78 Europa Ocidental', 503100);
INSERT INTO countries (region, key_word, name, population) VALUES ('Europa Ocidental', 2, 'País 79 Europa Ocidental', 694470);
INSERT INTO countries (region, key_word, name, population) VALUES ('Europa Ocidental', 1, 'País 80 Europa Ocidental', 545148);
INSERT INTO countries (region, key_word, name, population) VALUES ('Europa Ocidental', 2, 'País 81 Europa Ocidental', 588630);
INSERT INTO countries (region, key_word, name, population) VALUES ('Europa Ocidental', 2, 'País 82 Europa Ocidental', 362923);
INSERT INTO countries (region, key_word, name, population) VALUES ('Europa Ocidental', 2, 'País 83 Europa Ocidental', 229094);
INSERT INTO countries (region, key_word, name, population) VALUES ('Europa Ocidental', 2, 'País 84 Europa Ocidental', 370027);
INSERT INTO countries (region, key_word, name, population) VALUES ('Europa Ocidental', 2, 'País 85 Europa Ocidental', 593501);
INSERT INTO countries (region, key_word, name, population) VALUES ('Europa Ocidental', 1, 'País 86 Europa Ocidental', 627129);
INSERT INTO countries (region, key_word, name, population) VALUES ('Europa Ocidental', 3, 'País 87 Europa Ocidental', 139427);
INSERT INTO countries (region, key_word, name, population) VALUES ('Europa Ocidental', 3, 'País 88 Europa Ocidental', 440838);
INSERT INTO countries (region, key_word, name, population) VALUES ('Europa Ocidental', 1, 'País 89 Europa Ocidental', 204908);
INSERT INTO countries (region, key_word, name, population) VALUES ('Europa Ocidental', 3, 'País 90 Europa Ocidental', 977913);
INSERT INTO countries (region, key_word, name, population) VALUES ('Europa Ocidental', 2, 'País 91 Europa Ocidental', 753725);
INSERT INTO countries (region, key_word, name, population) VALUES ('Europa Ocidental', 1, 'País 92 Europa Ocidental', 803465);
INSERT INTO countries (region, key_word, name, population) VALUES ('Europa Ocidental', 3, 'País 93 Europa Ocidental', 634525);
INSERT INTO countries (region, key_word, name, population) VALUES ('Europa Ocidental', 3, 'País 94 Europa Ocidental', 345835);
INSERT INTO countries (region, key_word, name, population) VALUES ('Europa Ocidental', 2, 'País 95 Europa Ocidental', 340275);
INSERT INTO countries (region, key_word, name, population) VALUES ('Europa Ocidental', 2, 'País 96 Europa Ocidental', 286337);
INSERT INTO countries (region, key_word, name, population) VALUES ('Europa Ocidental', 1, 'País 97 Europa Ocidental', 291044);
INSERT INTO countries (region, key_word, name, population) VALUES ('Europa Ocidental', 1, 'País 98 Europa Ocidental', 891832);
INSERT INTO countries (region, key_word, name, population) VALUES ('Europa Ocidental', 3, 'País 99 Europa Ocidental', 779427);
INSERT INTO countries (region, key_word, name, population) VALUES ('Europa Ocidental', 3, 'País 100 Europa Ocidental', 592910);
INSERT INTO countries (region, key_word, name, population) VALUES ('Ásia Oriental', 3, 'País 1 Ásia Oriental', 268582);
INSERT INTO countries (region, key_word, name, population) VALUES ('Ásia Oriental', 1, 'País 2 Ásia Oriental', 872095);
INSERT INTO countries (region, key_word, name, population) VALUES ('Ásia Oriental', 3, 'País 3 Ásia Oriental', 128079);
INSERT INTO countries (region, key_word, name, population) VALUES ('Ásia Oriental', 1, 'País 4 Ásia Oriental', 459356);
INSERT INTO countries (region, key_word, name, population) VALUES ('Ásia Oriental', 2, 'País 5 Ásia Oriental', 582557);
INSERT INTO countries (region, key_word, name, population) VALUES ('Ásia Oriental', 3, 'País 6 Ásia Oriental', 179799);
INSERT INTO countries (region, key_word, name, population) VALUES ('Ásia Oriental', 1, 'País 7 Ásia Oriental', 756777);
INSERT INTO countries (region, key_word, name, population) VALUES ('Ásia Oriental', 1, 'País 8 Ásia Oriental', 203634);
INSERT INTO countries (region, key_word, name, population) VALUES ('Ásia Oriental', 2, 'País 9 Ásia Oriental', 390095);
INSERT INTO countries (region, key_word, name, population) VALUES ('Ásia Oriental', 3, 'País 10 Ásia Oriental', 715659);
INSERT INTO countries (region, key_word, name, population) VALUES ('Ásia Oriental', 2, 'País 11 Ásia Oriental', 782760);
INSERT INTO countries (region, key_word, name, population) VALUES ('Ásia Oriental', 2, 'País 12 Ásia Oriental', 674665);
INSERT INTO countries (region, key_word, name, population) VALUES ('Ásia Oriental', 1, 'País 13 Ásia Oriental', 389749);
INSERT INTO countries (region, key_word, name, population) VALUES ('Ásia Oriental', 3, 'País 14 Ásia Oriental', 399089);
INSERT INTO countries (region, key_word, name, population) VALUES ('Ásia Oriental', 1, 'País 15 Ásia Oriental', 438814);
INSERT INTO countries (region, key_word, name, population) VALUES ('Ásia Oriental', 1, 'País 16 Ásia Oriental', 525074);
INSERT INTO countries (region, key_word, name, population) VALUES ('Ásia Oriental', 2, 'País 17 Ásia Oriental', 764818);
INSERT INTO countries (region, key_word, name, population) VALUES ('Ásia Oriental', 3, 'País 18 Ásia Oriental', 226472);
INSERT INTO countries (region, key_word, name, population) VALUES ('Ásia Oriental', 1, 'País 19 Ásia Oriental', 204146);
INSERT INTO countries (region, key_word, name, population) VALUES ('Ásia Oriental', 1, 'País 20 Ásia Oriental', 579794);
INSERT INTO countries (region, key_word, name, population) VALUES ('Ásia Oriental', 3, 'País 21 Ásia Oriental', 922637);
INSERT INTO countries (region, key_word, name, population) VALUES ('Ásia Oriental', 3, 'País 22 Ásia Oriental', 214633);
INSERT INTO countries (region, key_word, name, population) VALUES ('Ásia Oriental', 2, 'País 23 Ásia Oriental', 566482);
INSERT INTO countries (region, key_word, name, population) VALUES ('Ásia Oriental', 3, 'País 24 Ásia Oriental', 631091);
INSERT INTO countries (region, key_word, name, population) VALUES ('Ásia Oriental', 1, 'País 25 Ásia Oriental', 761425);
INSERT INTO countries (region, key_word, name, population) VALUES ('Ásia Oriental', 1, 'País 26 Ásia Oriental', 373523);
INSERT INTO countries (region, key_word, name, population) VALUES ('Ásia Oriental', 1, 'País 27 Ásia Oriental', 299319);
INSERT INTO countries (region, key_word, name, population) VALUES ('Ásia Oriental', 2, 'País 28 Ásia Oriental', 871122);
INSERT INTO countries (region, key_word, name, population) VALUES ('Ásia Oriental', 2, 'País 29 Ásia Oriental', 892813);
INSERT INTO countries (region, key_word, name, population) VALUES ('Ásia Oriental', 1, 'País 30 Ásia Oriental', 898735);
INSERT INTO countries (region, key_word, name, population) VALUES ('Ásia Oriental', 2, 'País 31 Ásia Oriental', 812776);
INSERT INTO countries (region, key_word, name, population) VALUES ('Ásia Oriental', 1, 'País 32 Ásia Oriental', 880895);
INSERT INTO countries (region, key_word, name, population) VALUES ('Ásia Oriental', 1, 'País 33 Ásia Oriental', 455870);
INSERT INTO countries (region, key_word, name, population) VALUES ('Ásia Oriental', 1, 'País 34 Ásia Oriental', 907259);
INSERT INTO countries (region, key_word, name, population) VALUES ('Ásia Oriental', 1, 'País 35 Ásia Oriental', 376727);
INSERT INTO countries (region, key_word, name, population) VALUES ('Ásia Oriental', 2, 'País 36 Ásia Oriental', 948687);
INSERT INTO countries (region, key_word, name, population) VALUES ('Ásia Oriental', 1, 'País 37 Ásia Oriental', 212254);
INSERT INTO countries (region, key_word, name, population) VALUES ('Ásia Oriental', 3, 'País 38 Ásia Oriental', 535049);
INSERT INTO countries (region, key_word, name, population) VALUES ('Ásia Oriental', 2, 'País 39 Ásia Oriental', 805584);
INSERT INTO countries (region, key_word, name, population) VALUES ('Ásia Oriental', 1, 'País 40 Ásia Oriental', 962302);
INSERT INTO countries (region, key_word, name, population) VALUES ('Ásia Oriental', 2, 'País 41 Ásia Oriental', 727584);
INSERT INTO countries (region, key_word, name, population) VALUES ('Ásia Oriental', 3, 'País 42 Ásia Oriental', 293571);
INSERT INTO countries (region, key_word, name, population) VALUES ('Ásia Oriental', 2, 'País 43 Ásia Oriental', 929783);
INSERT INTO countries (region, key_word, name, population) VALUES ('Ásia Oriental', 1, 'País 44 Ásia Oriental', 481735);
INSERT INTO countries (region, key_word, name, population) VALUES ('Ásia Oriental', 1, 'País 45 Ásia Oriental', 130616);
INSERT INTO countries (region, key_word, name, population) VALUES ('Ásia Oriental', 3, 'País 46 Ásia Oriental', 259242);
INSERT INTO countries (region, key_word, name, population) VALUES ('Ásia Oriental', 3, 'País 47 Ásia Oriental', 483582);
INSERT INTO countries (region, key_word, name, population) VALUES ('Ásia Oriental', 1, 'País 48 Ásia Oriental', 192682);
INSERT INTO countries (region, key_word, name, population) VALUES ('Ásia Oriental', 2, 'País 49 Ásia Oriental', 651168);
INSERT INTO countries (region, key_word, name, population) VALUES ('Ásia Oriental', 1, 'País 50 Ásia Oriental', 775324);
INSERT INTO countries (region, key_word, name, population) VALUES ('Ásia Oriental', 1, 'País 51 Ásia Oriental', 558192);
INSERT INTO countries (region, key_word, name, population) VALUES ('Ásia Oriental', 3, 'País 52 Ásia Oriental', 740788);
INSERT INTO countries (region, key_word, name, population) VALUES ('Ásia Oriental', 2, 'País 53 Ásia Oriental', 115493);
INSERT INTO countries (region, key_word, name, population) VALUES ('Ásia Oriental', 2, 'País 54 Ásia Oriental', 264122);
INSERT INTO countries (region, key_word, name, population) VALUES ('Ásia Oriental', 2, 'País 55 Ásia Oriental', 121402);
INSERT INTO countries (region, key_word, name, population) VALUES ('Ásia Oriental', 3, 'País 56 Ásia Oriental', 850531);
INSERT INTO countries (region, key_word, name, population) VALUES ('Ásia Oriental', 2, 'País 57 Ásia Oriental', 896561);
INSERT INTO countries (region, key_word, name, population) VALUES ('Ásia Oriental', 1, 'País 58 Ásia Oriental', 139258);
INSERT INTO countries (region, key_word, name, population) VALUES ('Ásia Oriental', 2, 'País 59 Ásia Oriental', 518102);
INSERT INTO countries (region, key_word, name, population) VALUES ('Ásia Oriental', 2, 'País 60 Ásia Oriental', 250565);
INSERT INTO countries (region, key_word, name, population) VALUES ('Ásia Oriental', 1, 'País 61 Ásia Oriental', 564029);
INSERT INTO countries (region, key_word, name, population) VALUES ('Ásia Oriental', 1, 'País 62 Ásia Oriental', 951878);
INSERT INTO countries (region, key_word, name, population) VALUES ('Ásia Oriental', 2, 'País 63 Ásia Oriental', 842185);
INSERT INTO countries (region, key_word, name, population) VALUES ('Ásia Oriental', 3, 'País 64 Ásia Oriental', 309955);
INSERT INTO countries (region, key_word, name, population) VALUES ('Ásia Oriental', 1, 'País 65 Ásia Oriental', 427580);
INSERT INTO countries (region, key_word, name, population) VALUES ('Ásia Oriental', 1, 'País 66 Ásia Oriental', 376267);
INSERT INTO countries (region, key_word, name, population) VALUES ('Ásia Oriental', 1, 'País 67 Ásia Oriental', 902835);
INSERT INTO countries (region, key_word, name, population) VALUES ('Ásia Oriental', 1, 'País 68 Ásia Oriental', 683607);
INSERT INTO countries (region, key_word, name, population) VALUES ('Ásia Oriental', 1, 'País 69 Ásia Oriental', 608375);
INSERT INTO countries (region, key_word, name, population) VALUES ('Ásia Oriental', 3, 'País 70 Ásia Oriental', 386271);
INSERT INTO countries (region, key_word, name, population) VALUES ('Ásia Oriental', 1, 'País 71 Ásia Oriental', 243408);
INSERT INTO countries (region, key_word, name, population) VALUES ('Ásia Oriental', 2, 'País 72 Ásia Oriental', 334421);
INSERT INTO countries (region, key_word, name, population) VALUES ('Ásia Oriental', 3, 'País 73 Ásia Oriental', 205215);
INSERT INTO countries (region, key_word, name, population) VALUES ('Ásia Oriental', 3, 'País 74 Ásia Oriental', 390650);
INSERT INTO countries (region, key_word, name, population) VALUES ('Ásia Oriental', 2, 'País 75 Ásia Oriental', 150050);
INSERT INTO countries (region, key_word, name, population) VALUES ('Ásia Oriental', 1, 'País 76 Ásia Oriental', 648519);
INSERT INTO countries (region, key_word, name, population) VALUES ('Ásia Oriental', 3, 'País 77 Ásia Oriental', 358453);
INSERT INTO countries (region, key_word, name, population) VALUES ('Ásia Oriental', 1, 'País 78 Ásia Oriental', 108118);
INSERT INTO countries (region, key_word, name, population) VALUES ('Ásia Oriental', 1, 'País 79 Ásia Oriental', 946008);
INSERT INTO countries (region, key_word, name, population) VALUES ('Ásia Oriental', 2, 'País 80 Ásia Oriental', 870310);
INSERT INTO countries (region, key_word, name, population) VALUES ('Ásia Oriental', 1, 'País 81 Ásia Oriental', 428136);
INSERT INTO countries (region, key_word, name, population) VALUES ('Ásia Oriental', 2, 'País 82 Ásia Oriental', 396289);
INSERT INTO countries (region, key_word, name, population) VALUES ('Ásia Oriental', 1, 'País 83 Ásia Oriental', 233901);
INSERT INTO countries (region, key_word, name, population) VALUES ('Ásia Oriental', 2, 'País 84 Ásia Oriental', 502917);
INSERT INTO countries (region, key_word, name, population) VALUES ('Ásia Oriental', 2, 'País 85 Ásia Oriental', 442672);
INSERT INTO countries (region, key_word, name, population) VALUES ('Ásia Oriental', 3, 'País 86 Ásia Oriental', 873013);
INSERT INTO countries (region, key_word, name, population) VALUES ('Ásia Oriental', 3, 'País 87 Ásia Oriental', 460334);
INSERT INTO countries (region, key_word, name, population) VALUES ('Ásia Oriental', 1, 'País 88 Ásia Oriental', 717948);
INSERT INTO countries (region, key_word, name, population) VALUES ('Ásia Oriental', 1, 'País 89 Ásia Oriental', 921371);
INSERT INTO countries (region, key_word, name, population) VALUES ('Ásia Oriental', 1, 'País 90 Ásia Oriental', 897142);
INSERT INTO countries (region, key_word, name, population) VALUES ('Ásia Oriental', 1, 'País 91 Ásia Oriental', 672095);
INSERT INTO countries (region, key_word, name, population) VALUES ('Ásia Oriental', 2, 'País 92 Ásia Oriental', 835232);
INSERT INTO countries (region, key_word, name, population) VALUES ('Ásia Oriental', 2, 'País 93 Ásia Oriental', 945202);
INSERT INTO countries (region, key_word, name, population) VALUES ('Ásia Oriental', 2, 'País 94 Ásia Oriental', 908515);
INSERT INTO countries (region, key_word, name, population) VALUES ('Ásia Oriental', 3, 'País 95 Ásia Oriental', 763437);
INSERT INTO countries (region, key_word, name, population) VALUES ('Ásia Oriental', 3, 'País 96 Ásia Oriental', 593761);
INSERT INTO countries (region, key_word, name, population) VALUES ('Ásia Oriental', 3, 'País 97 Ásia Oriental', 678596);
INSERT INTO countries (region, key_word, name, population) VALUES ('Ásia Oriental', 2, 'País 98 Ásia Oriental', 857929);
INSERT INTO countries (region, key_word, name, population) VALUES ('Ásia Oriental', 3, 'País 99 Ásia Oriental', 542145);
INSERT INTO countries (region, key_word, name, population) VALUES ('Ásia Oriental', 1, 'País 100 Ásia Oriental', 777213);
INSERT INTO countries (region, key_word, name, population) VALUES ('África Subsaariana', 2, 'País 1 África Subsaariana', 914871);
INSERT INTO countries (region, key_word, name, population) VALUES ('África Subsaariana', 1, 'País 2 África Subsaariana', 412552);
INSERT INTO countries (region, key_word, name, population) VALUES ('África Subsaariana', 1, 'País 3 África Subsaariana', 121887);
INSERT INTO countries (region, key_word, name, population) VALUES ('África Subsaariana', 1, 'País 4 África Subsaariana', 873126);
INSERT INTO countries (region, key_word, name, population) VALUES ('África Subsaariana', 3, 'País 5 África Subsaariana', 694829);
INSERT INTO countries (region, key_word, name, population) VALUES ('África Subsaariana', 1, 'País 6 África Subsaariana', 776719);
INSERT INTO countries (region, key_word, name, population) VALUES ('África Subsaariana', 3, 'País 7 África Subsaariana', 700730);
INSERT INTO countries (region, key_word, name, population) VALUES ('África Subsaariana', 1, 'País 8 África Subsaariana', 366253);
INSERT INTO countries (region, key_word, name, population) VALUES ('África Subsaariana', 1, 'País 9 África Subsaariana', 976369);
INSERT INTO countries (region, key_word, name, population) VALUES ('África Subsaariana', 2, 'País 10 África Subsaariana', 429283);
INSERT INTO countries (region, key_word, name, population) VALUES ('África Subsaariana', 2, 'País 11 África Subsaariana', 372689);
INSERT INTO countries (region, key_word, name, population) VALUES ('África Subsaariana', 3, 'País 12 África Subsaariana', 134032);
INSERT INTO countries (region, key_word, name, population) VALUES ('África Subsaariana', 2, 'País 13 África Subsaariana', 649072);
INSERT INTO countries (region, key_word, name, population) VALUES ('África Subsaariana', 1, 'País 14 África Subsaariana', 954397);
INSERT INTO countries (region, key_word, name, population) VALUES ('África Subsaariana', 2, 'País 15 África Subsaariana', 983574);
INSERT INTO countries (region, key_word, name, population) VALUES ('África Subsaariana', 3, 'País 16 África Subsaariana', 126494);
INSERT INTO countries (region, key_word, name, population) VALUES ('África Subsaariana', 3, 'País 17 África Subsaariana', 110884);
INSERT INTO countries (region, key_word, name, population) VALUES ('África Subsaariana', 2, 'País 18 África Subsaariana', 214448);
INSERT INTO countries (region, key_word, name, population) VALUES ('África Subsaariana', 3, 'País 19 África Subsaariana', 711439);
INSERT INTO countries (region, key_word, name, population) VALUES ('África Subsaariana', 2, 'País 20 África Subsaariana', 323287);
INSERT INTO countries (region, key_word, name, population) VALUES ('África Subsaariana', 3, 'País 21 África Subsaariana', 545308);
INSERT INTO countries (region, key_word, name, population) VALUES ('África Subsaariana', 3, 'País 22 África Subsaariana', 675030);
INSERT INTO countries (region, key_word, name, population) VALUES ('África Subsaariana', 2, 'País 23 África Subsaariana', 694739);
INSERT INTO countries (region, key_word, name, population) VALUES ('África Subsaariana', 2, 'País 24 África Subsaariana', 367635);
INSERT INTO countries (region, key_word, name, population) VALUES ('África Subsaariana', 1, 'País 25 África Subsaariana', 746061);
INSERT INTO countries (region, key_word, name, population) VALUES ('África Subsaariana', 3, 'País 26 África Subsaariana', 931801);
INSERT INTO countries (region, key_word, name, population) VALUES ('África Subsaariana', 1, 'País 27 África Subsaariana', 857525);
INSERT INTO countries (region, key_word, name, population) VALUES ('África Subsaariana', 1, 'País 28 África Subsaariana', 409905);
INSERT INTO countries (region, key_word, name, population) VALUES ('África Subsaariana', 3, 'País 29 África Subsaariana', 307416);
INSERT INTO countries (region, key_word, name, population) VALUES ('África Subsaariana', 1, 'País 30 África Subsaariana', 495735);
INSERT INTO countries (region, key_word, name, population) VALUES ('África Subsaariana', 1, 'País 31 África Subsaariana', 631867);
INSERT INTO countries (region, key_word, name, population) VALUES ('África Subsaariana', 2, 'País 32 África Subsaariana', 368681);
INSERT INTO countries (region, key_word, name, population) VALUES ('África Subsaariana', 3, 'País 33 África Subsaariana', 672794);
INSERT INTO countries (region, key_word, name, population) VALUES ('África Subsaariana', 1, 'País 34 África Subsaariana', 500615);
INSERT INTO countries (region, key_word, name, population) VALUES ('África Subsaariana', 3, 'País 35 África Subsaariana', 633935);
INSERT INTO countries (region, key_word, name, population) VALUES ('África Subsaariana', 3, 'País 36 África Subsaariana', 205510);
INSERT INTO countries (region, key_word, name, population) VALUES ('África Subsaariana', 3, 'País 37 África Subsaariana', 780632);
INSERT INTO countries (region, key_word, name, population) VALUES ('África Subsaariana', 1, 'País 38 África Subsaariana', 937024);
INSERT INTO countries (region, key_word, name, population) VALUES ('África Subsaariana', 1, 'País 39 África Subsaariana', 686559);
INSERT INTO countries (region, key_word, name, population) VALUES ('África Subsaariana', 3, 'País 40 África Subsaariana', 492578);
INSERT INTO countries (region, key_word, name, population) VALUES ('África Subsaariana', 2, 'País 41 África Subsaariana', 785508);
INSERT INTO countries (region, key_word, name, population) VALUES ('África Subsaariana', 1, 'País 42 África Subsaariana', 794992);
INSERT INTO countries (region, key_word, name, population) VALUES ('África Subsaariana', 3, 'País 43 África Subsaariana', 553271);
INSERT INTO countries (region, key_word, name, population) VALUES ('África Subsaariana', 2, 'País 44 África Subsaariana', 399852);
INSERT INTO countries (region, key_word, name, population) VALUES ('África Subsaariana', 3, 'País 45 África Subsaariana', 519616);
INSERT INTO countries (region, key_word, name, population) VALUES ('África Subsaariana', 3, 'País 46 África Subsaariana', 745661);
INSERT INTO countries (region, key_word, name, population) VALUES ('África Subsaariana', 1, 'País 47 África Subsaariana', 596380);
INSERT INTO countries (region, key_word, name, population) VALUES ('África Subsaariana', 3, 'País 48 África Subsaariana', 341786);
INSERT INTO countries (region, key_word, name, population) VALUES ('África Subsaariana', 2, 'País 49 África Subsaariana', 664733);
INSERT INTO countries (region, key_word, name, population) VALUES ('África Subsaariana', 3, 'País 50 África Subsaariana', 199082);
INSERT INTO countries (region, key_word, name, population) VALUES ('África Subsaariana', 3, 'País 51 África Subsaariana', 638134);
INSERT INTO countries (region, key_word, name, population) VALUES ('África Subsaariana', 1, 'País 52 África Subsaariana', 798395);
INSERT INTO countries (region, key_word, name, population) VALUES ('África Subsaariana', 2, 'País 53 África Subsaariana', 497454);
INSERT INTO countries (region, key_word, name, population) VALUES ('África Subsaariana', 1, 'País 54 África Subsaariana', 705408);
INSERT INTO countries (region, key_word, name, population) VALUES ('África Subsaariana', 3, 'País 55 África Subsaariana', 996696);
INSERT INTO countries (region, key_word, name, population) VALUES ('África Subsaariana', 3, 'País 56 África Subsaariana', 412568);
INSERT INTO countries (region, key_word, name, population) VALUES ('África Subsaariana', 2, 'País 57 África Subsaariana', 921462);
INSERT INTO countries (region, key_word, name, population) VALUES ('África Subsaariana', 3, 'País 58 África Subsaariana', 756630);
INSERT INTO countries (region, key_word, name, population) VALUES ('África Subsaariana', 2, 'País 59 África Subsaariana', 492652);
INSERT INTO countries (region, key_word, name, population) VALUES ('África Subsaariana', 2, 'País 60 África Subsaariana', 352444);
INSERT INTO countries (region, key_word, name, population) VALUES ('África Subsaariana', 1, 'País 61 África Subsaariana', 585139);
INSERT INTO countries (region, key_word, name, population) VALUES ('África Subsaariana', 3, 'País 62 África Subsaariana', 163165);
INSERT INTO countries (region, key_word, name, population) VALUES ('África Subsaariana', 3, 'País 63 África Subsaariana', 729315);
INSERT INTO countries (region, key_word, name, population) VALUES ('África Subsaariana', 1, 'País 64 África Subsaariana', 265064);
INSERT INTO countries (region, key_word, name, population) VALUES ('África Subsaariana', 1, 'País 65 África Subsaariana', 668465);
INSERT INTO countries (region, key_word, name, population) VALUES ('África Subsaariana', 3, 'País 66 África Subsaariana', 674178);
INSERT INTO countries (region, key_word, name, population) VALUES ('África Subsaariana', 1, 'País 67 África Subsaariana', 811547);
INSERT INTO countries (region, key_word, name, population) VALUES ('África Subsaariana', 3, 'País 68 África Subsaariana', 879663);
INSERT INTO countries (region, key_word, name, population) VALUES ('África Subsaariana', 3, 'País 69 África Subsaariana', 968769);
INSERT INTO countries (region, key_word, name, population) VALUES ('África Subsaariana', 2, 'País 70 África Subsaariana', 771232);
INSERT INTO countries (region, key_word, name, population) VALUES ('África Subsaariana', 1, 'País 71 África Subsaariana', 930498);
INSERT INTO countries (region, key_word, name, population) VALUES ('África Subsaariana', 3, 'País 72 África Subsaariana', 376512);
INSERT INTO countries (region, key_word, name, population) VALUES ('África Subsaariana', 1, 'País 73 África Subsaariana', 747552);
INSERT INTO countries (region, key_word, name, population) VALUES ('África Subsaariana', 2, 'País 74 África Subsaariana', 880309);
INSERT INTO countries (region, key_word, name, population) VALUES ('África Subsaariana', 3, 'País 75 África Subsaariana', 389424);
INSERT INTO countries (region, key_word, name, population) VALUES ('África Subsaariana', 1, 'País 76 África Subsaariana', 706054);
INSERT INTO countries (region, key_word, name, population) VALUES ('África Subsaariana', 3, 'País 77 África Subsaariana', 901762);
INSERT INTO countries (region, key_word, name, population) VALUES ('África Subsaariana', 3, 'País 78 África Subsaariana', 969946);
INSERT INTO countries (region, key_word, name, population) VALUES ('África Subsaariana', 3, 'País 79 África Subsaariana', 330268);
INSERT INTO countries (region, key_word, name, population) VALUES ('África Subsaariana', 3, 'País 80 África Subsaariana', 289970);
INSERT INTO countries (region, key_word, name, population) VALUES ('África Subsaariana', 2, 'País 81 África Subsaariana', 121321);
INSERT INTO countries (region, key_word, name, population) VALUES ('África Subsaariana', 1, 'País 82 África Subsaariana', 901802);
INSERT INTO countries (region, key_word, name, population) VALUES ('África Subsaariana', 3, 'País 83 África Subsaariana', 258226);
INSERT INTO countries (region, key_word, name, population) VALUES ('África Subsaariana', 1, 'País 84 África Subsaariana', 343503);
INSERT INTO countries (region, key_word, name, population) VALUES ('África Subsaariana', 3, 'País 85 África Subsaariana', 526169);
INSERT INTO countries (region, key_word, name, population) VALUES ('África Subsaariana', 3, 'País 86 África Subsaariana', 797370);
INSERT INTO countries (region, key_word, name, population) VALUES ('África Subsaariana', 2, 'País 87 África Subsaariana', 989943);
INSERT INTO countries (region, key_word, name, population) VALUES ('África Subsaariana', 3, 'País 88 África Subsaariana', 232686);
INSERT INTO countries (region, key_word, name, population) VALUES ('África Subsaariana', 1, 'País 89 África Subsaariana', 504430);
INSERT INTO countries (region, key_word, name, population) VALUES ('África Subsaariana', 2, 'País 90 África Subsaariana', 367485);
INSERT INTO countries (region, key_word, name, population) VALUES ('África Subsaariana', 2, 'País 91 África Subsaariana', 227929);
INSERT INTO countries (region, key_word, name, population) VALUES ('África Subsaariana', 3, 'País 92 África Subsaariana', 637244);
INSERT INTO countries (region, key_word, name, population) VALUES ('África Subsaariana', 1, 'País 93 África Subsaariana', 340300);
INSERT INTO countries (region, key_word, name, population) VALUES ('África Subsaariana', 3, 'País 94 África Subsaariana', 421550);
INSERT INTO countries (region, key_word, name, population) VALUES ('África Subsaariana', 3, 'País 95 África Subsaariana', 326424);
INSERT INTO countries (region, key_word, name, population) VALUES ('África Subsaariana', 3, 'País 96 África Subsaariana', 340027);
INSERT INTO countries (region, key_word, name, population) VALUES ('África Subsaariana', 1, 'País 97 África Subsaariana', 811826);
INSERT INTO countries (region, key_word, name, population) VALUES ('África Subsaariana', 3, 'País 98 África Subsaariana', 942768);
INSERT INTO countries (region, key_word, name, population) VALUES ('África Subsaariana', 3, 'País 99 África Subsaariana', 582664);
INSERT INTO countries (region, key_word, name, population) VALUES ('África Subsaariana', 3, 'País 100 África Subsaariana', 270248);
INSERT INTO countries (region, key_word, name, population) VALUES ('Oceania', 3, 'País 1 Oceania', 212586);
INSERT INTO countries (region, key_word, name, population) VALUES ('Oceania', 1, 'País 2 Oceania', 485452);
INSERT INTO countries (region, key_word, name, population) VALUES ('Oceania', 1, 'País 3 Oceania', 994175);
INSERT INTO countries (region, key_word, name, population) VALUES ('Oceania', 2, 'País 4 Oceania', 409027);
INSERT INTO countries (region, key_word, name, population) VALUES ('Oceania', 2, 'País 5 Oceania', 303757);
INSERT INTO countries (region, key_word, name, population) VALUES ('Oceania', 1, 'País 6 Oceania', 782095);
INSERT INTO countries (region, key_word, name, population) VALUES ('Oceania', 2, 'País 7 Oceania', 797366);
INSERT INTO countries (region, key_word, name, population) VALUES ('Oceania', 3, 'País 8 Oceania', 548943);
INSERT INTO countries (region, key_word, name, population) VALUES ('Oceania', 2, 'País 9 Oceania', 820872);
INSERT INTO countries (region, key_word, name, population) VALUES ('Oceania', 3, 'País 10 Oceania', 346227);
INSERT INTO countries (region, key_word, name, population) VALUES ('Oceania', 2, 'País 11 Oceania', 429680);
INSERT INTO countries (region, key_word, name, population) VALUES ('Oceania', 2, 'País 12 Oceania', 943653);
INSERT INTO countries (region, key_word, name, population) VALUES ('Oceania', 3, 'País 13 Oceania', 406897);
INSERT INTO countries (region, key_word, name, population) VALUES ('Oceania', 2, 'País 14 Oceania', 899974);
INSERT INTO countries (region, key_word, name, population) VALUES ('Oceania', 2, 'País 15 Oceania', 989290);
INSERT INTO countries (region, key_word, name, population) VALUES ('Oceania', 1, 'País 16 Oceania', 390372);
INSERT INTO countries (region, key_word, name, population) VALUES ('Oceania', 2, 'País 17 Oceania', 245014);
INSERT INTO countries (region, key_word, name, population) VALUES ('Oceania', 2, 'País 18 Oceania', 479925);
INSERT INTO countries (region, key_word, name, population) VALUES ('Oceania', 3, 'País 19 Oceania', 341665);
INSERT INTO countries (region, key_word, name, population) VALUES ('Oceania', 2, 'País 20 Oceania', 264899);
INSERT INTO countries (region, key_word, name, population) VALUES ('Oceania', 3, 'País 21 Oceania', 790107);
INSERT INTO countries (region, key_word, name, population) VALUES ('Oceania', 2, 'País 22 Oceania', 108983);
INSERT INTO countries (region, key_word, name, population) VALUES ('Oceania', 1, 'País 23 Oceania', 908628);
INSERT INTO countries (region, key_word, name, population) VALUES ('Oceania', 2, 'País 24 Oceania', 368557);
INSERT INTO countries (region, key_word, name, population) VALUES ('Oceania', 3, 'País 25 Oceania', 377880);
INSERT INTO countries (region, key_word, name, population) VALUES ('Oceania', 1, 'País 26 Oceania', 337257);
INSERT INTO countries (region, key_word, name, population) VALUES ('Oceania', 1, 'País 27 Oceania', 747256);
INSERT INTO countries (region, key_word, name, population) VALUES ('Oceania', 1, 'País 28 Oceania', 927321);
INSERT INTO countries (region, key_word, name, population) VALUES ('Oceania', 2, 'País 29 Oceania', 186032);
INSERT INTO countries (region, key_word, name, population) VALUES ('Oceania', 3, 'País 30 Oceania', 738697);
INSERT INTO countries (region, key_word, name, population) VALUES ('Oceania', 1, 'País 31 Oceania', 474955);
INSERT INTO countries (region, key_word, name, population) VALUES ('Oceania', 3, 'País 32 Oceania', 965392);
INSERT INTO countries (region, key_word, name, population) VALUES ('Oceania', 1, 'País 33 Oceania', 428595);
INSERT INTO countries (region, key_word, name, population) VALUES ('Oceania', 2, 'País 34 Oceania', 711965);
INSERT INTO countries (region, key_word, name, population) VALUES ('Oceania', 3, 'País 35 Oceania', 417853);
INSERT INTO countries (region, key_word, name, population) VALUES ('Oceania', 2, 'País 36 Oceania', 411905);
INSERT INTO countries (region, key_word, name, population) VALUES ('Oceania', 2, 'País 37 Oceania', 797072);
INSERT INTO countries (region, key_word, name, population) VALUES ('Oceania', 2, 'País 38 Oceania', 107255);
INSERT INTO countries (region, key_word, name, population) VALUES ('Oceania', 2, 'País 39 Oceania', 965905);
INSERT INTO countries (region, key_word, name, population) VALUES ('Oceania', 1, 'País 40 Oceania', 719002);
INSERT INTO countries (region, key_word, name, population) VALUES ('Oceania', 3, 'País 41 Oceania', 820422);
INSERT INTO countries (region, key_word, name, population) VALUES ('Oceania', 2, 'País 42 Oceania', 268544);
INSERT INTO countries (region, key_word, name, population) VALUES ('Oceania', 1, 'País 43 Oceania', 860152);
INSERT INTO countries (region, key_word, name, population) VALUES ('Oceania', 2, 'País 44 Oceania', 247230);
INSERT INTO countries (region, key_word, name, population) VALUES ('Oceania', 1, 'País 45 Oceania', 466858);
INSERT INTO countries (region, key_word, name, population) VALUES ('Oceania', 2, 'País 46 Oceania', 302579);
INSERT INTO countries (region, key_word, name, population) VALUES ('Oceania', 3, 'País 47 Oceania', 342433);
INSERT INTO countries (region, key_word, name, population) VALUES ('Oceania', 2, 'País 48 Oceania', 443853);
INSERT INTO countries (region, key_word, name, population) VALUES ('Oceania', 2, 'País 49 Oceania', 334080);
INSERT INTO countries (region, key_word, name, population) VALUES ('Oceania', 1, 'País 50 Oceania', 955906);
INSERT INTO countries (region, key_word, name, population) VALUES ('Oceania', 3, 'País 51 Oceania', 635725);
INSERT INTO countries (region, key_word, name, population) VALUES ('Oceania', 3, 'País 52 Oceania', 601763);
INSERT INTO countries (region, key_word, name, population) VALUES ('Oceania', 2, 'País 53 Oceania', 364948);
INSERT INTO countries (region, key_word, name, population) VALUES ('Oceania', 1, 'País 54 Oceania', 692290);
INSERT INTO countries (region, key_word, name, population) VALUES ('Oceania', 1, 'País 55 Oceania', 277016);
INSERT INTO countries (region, key_word, name, population) VALUES ('Oceania', 3, 'País 56 Oceania', 737309);
INSERT INTO countries (region, key_word, name, population) VALUES ('Oceania', 3, 'País 57 Oceania', 149124);
INSERT INTO countries (region, key_word, name, population) VALUES ('Oceania', 1, 'País 58 Oceania', 245811);
INSERT INTO countries (region, key_word, name, population) VALUES ('Oceania', 2, 'País 59 Oceania', 776462);
INSERT INTO countries (region, key_word, name, population) VALUES ('Oceania', 2, 'País 60 Oceania', 606952);
INSERT INTO countries (region, key_word, name, population) VALUES ('Oceania', 2, 'País 61 Oceania', 809225);
INSERT INTO countries (region, key_word, name, population) VALUES ('Oceania', 2, 'País 62 Oceania', 773134);
INSERT INTO countries (region, key_word, name, population) VALUES ('Oceania', 2, 'País 63 Oceania', 343852);
INSERT INTO countries (region, key_word, name, population) VALUES ('Oceania', 2, 'País 64 Oceania', 785583);
INSERT INTO countries (region, key_word, name, population) VALUES ('Oceania', 1, 'País 65 Oceania', 497512);
INSERT INTO countries (region, key_word, name, population) VALUES ('Oceania', 1, 'País 66 Oceania', 731319);
INSERT INTO countries (region, key_word, name, population) VALUES ('Oceania', 3, 'País 67 Oceania', 250836);
INSERT INTO countries (region, key_word, name, population) VALUES ('Oceania', 2, 'País 68 Oceania', 779278);
INSERT INTO countries (region, key_word, name, population) VALUES ('Oceania', 2, 'País 69 Oceania', 371203);
INSERT INTO countries (region, key_word, name, population) VALUES ('Oceania', 1, 'País 70 Oceania', 732697);
INSERT INTO countries (region, key_word, name, population) VALUES ('Oceania', 3, 'País 71 Oceania', 388294);
INSERT INTO countries (region, key_word, name, population) VALUES ('Oceania', 3, 'País 72 Oceania', 740278);
INSERT INTO countries (region, key_word, name, population) VALUES ('Oceania', 1, 'País 73 Oceania', 818011);
INSERT INTO countries (region, key_word, name, population) VALUES ('Oceania', 1, 'País 74 Oceania', 782012);
INSERT INTO countries (region, key_word, name, population) VALUES ('Oceania', 1, 'País 75 Oceania', 907263);
INSERT INTO countries (region, key_word, name, population) VALUES ('Oceania', 3, 'País 76 Oceania', 354844);
INSERT INTO countries (region, key_word, name, population) VALUES ('Oceania', 3, 'País 77 Oceania', 657041);
INSERT INTO countries (region, key_word, name, population) VALUES ('Oceania', 2, 'País 78 Oceania', 370186);
INSERT INTO countries (region, key_word, name, population) VALUES ('Oceania', 3, 'País 79 Oceania', 621772);
INSERT INTO countries (region, key_word, name, population) VALUES ('Oceania', 1, 'País 80 Oceania', 378083);
INSERT INTO countries (region, key_word, name, population) VALUES ('Oceania', 2, 'País 81 Oceania', 580323);
INSERT INTO countries (region, key_word, name, population) VALUES ('Oceania', 2, 'País 82 Oceania', 938405);
INSERT INTO countries (region, key_word, name, population) VALUES ('Oceania', 3, 'País 83 Oceania', 668706);
INSERT INTO countries (region, key_word, name, population) VALUES ('Oceania', 2, 'País 84 Oceania', 797288);
INSERT INTO countries (region, key_word, name, population) VALUES ('Oceania', 3, 'País 85 Oceania', 258213);
INSERT INTO countries (region, key_word, name, population) VALUES ('Oceania', 2, 'País 86 Oceania', 546626);
INSERT INTO countries (region, key_word, name, population) VALUES ('Oceania', 1, 'País 87 Oceania', 648308);
INSERT INTO countries (region, key_word, name, population) VALUES ('Oceania', 3, 'País 88 Oceania', 939154);
INSERT INTO countries (region, key_word, name, population) VALUES ('Oceania', 1, 'País 89 Oceania', 720132);
INSERT INTO countries (region, key_word, name, population) VALUES ('Oceania', 3, 'País 90 Oceania', 496331);
INSERT INTO countries (region, key_word, name, population) VALUES ('Oceania', 2, 'País 91 Oceania', 701312);
INSERT INTO countries (region, key_word, name, population) VALUES ('Oceania', 2, 'País 92 Oceania', 437700);
INSERT INTO countries (region, key_word, name, population) VALUES ('Oceania', 2, 'País 93 Oceania', 496686);
INSERT INTO countries (region, key_word, name, population) VALUES ('Oceania', 3, 'País 94 Oceania', 553822);
INSERT INTO countries (region, key_word, name, population) VALUES ('Oceania', 2, 'País 95 Oceania', 235896);
INSERT INTO countries (region, key_word, name, population) VALUES ('Oceania', 3, 'País 96 Oceania', 170960);
INSERT INTO countries (region, key_word, name, population) VALUES ('Oceania', 3, 'País 97 Oceania', 357767);
INSERT INTO countries (region, key_word, name, population) VALUES ('Oceania', 3, 'País 98 Oceania', 981616);
INSERT INTO countries (region, key_word, name, population) VALUES ('Oceania', 3, 'País 99 Oceania', 805121);
INSERT INTO countries (region, key_word, name, population) VALUES ('Oceania', 1, 'País 100 Oceania', 574866);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Sul', 2, 'País 1 América do Sul', 285126);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Sul', 3, 'País 2 América do Sul', 554804);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Sul', 1, 'País 3 América do Sul', 217773);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Sul', 3, 'País 4 América do Sul', 658025);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Sul', 3, 'País 5 América do Sul', 505856);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Sul', 3, 'País 6 América do Sul', 467294);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Sul', 3, 'País 7 América do Sul', 704142);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Sul', 1, 'País 8 América do Sul', 152165);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Sul', 1, 'País 9 América do Sul', 479903);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Sul', 2, 'País 10 América do Sul', 650728);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Sul', 2, 'País 11 América do Sul', 812503);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Sul', 1, 'País 12 América do Sul', 213715);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Sul', 2, 'País 13 América do Sul', 966734);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Sul', 3, 'País 14 América do Sul', 127205);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Sul', 1, 'País 15 América do Sul', 143483);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Sul', 3, 'País 16 América do Sul', 199609);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Sul', 3, 'País 17 América do Sul', 277811);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Sul', 3, 'País 18 América do Sul', 177515);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Sul', 1, 'País 19 América do Sul', 566744);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Sul', 3, 'País 20 América do Sul', 486752);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Sul', 2, 'País 21 América do Sul', 823725);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Sul', 3, 'País 22 América do Sul', 508593);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Sul', 2, 'País 23 América do Sul', 280119);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Sul', 1, 'País 24 América do Sul', 537121);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Sul', 2, 'País 25 América do Sul', 767807);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Sul', 1, 'País 26 América do Sul', 830873);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Sul', 2, 'País 27 América do Sul', 750175);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Sul', 1, 'País 28 América do Sul', 302859);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Sul', 3, 'País 29 América do Sul', 289639);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Sul', 1, 'País 30 América do Sul', 501878);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Sul', 3, 'País 31 América do Sul', 645405);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Sul', 1, 'País 32 América do Sul', 381043);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Sul', 1, 'País 33 América do Sul', 358112);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Sul', 1, 'País 34 América do Sul', 134837);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Sul', 2, 'País 35 América do Sul', 291189);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Sul', 3, 'País 36 América do Sul', 755916);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Sul', 1, 'País 37 América do Sul', 163820);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Sul', 1, 'País 38 América do Sul', 139629);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Sul', 3, 'País 39 América do Sul', 406514);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Sul', 2, 'País 40 América do Sul', 184325);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Sul', 2, 'País 41 América do Sul', 198775);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Sul', 2, 'País 42 América do Sul', 657375);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Sul', 3, 'País 43 América do Sul', 161582);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Sul', 2, 'País 44 América do Sul', 649786);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Sul', 1, 'País 45 América do Sul', 423592);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Sul', 2, 'País 46 América do Sul', 365496);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Sul', 1, 'País 47 América do Sul', 915042);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Sul', 2, 'País 48 América do Sul', 744855);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Sul', 1, 'País 49 América do Sul', 582235);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Sul', 3, 'País 50 América do Sul', 603215);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Sul', 1, 'País 51 América do Sul', 448149);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Sul', 2, 'País 52 América do Sul', 202544);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Sul', 2, 'País 53 América do Sul', 947905);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Sul', 3, 'País 54 América do Sul', 393735);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Sul', 3, 'País 55 América do Sul', 990902);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Sul', 2, 'País 56 América do Sul', 549884);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Sul', 2, 'País 57 América do Sul', 966735);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Sul', 3, 'País 58 América do Sul', 529135);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Sul', 3, 'País 59 América do Sul', 625634);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Sul', 3, 'País 60 América do Sul', 791724);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Sul', 1, 'País 61 América do Sul', 228764);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Sul', 3, 'País 62 América do Sul', 711220);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Sul', 2, 'País 63 América do Sul', 707643);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Sul', 2, 'País 64 América do Sul', 849688);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Sul', 1, 'País 65 América do Sul', 579994);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Sul', 3, 'País 66 América do Sul', 673952);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Sul', 3, 'País 67 América do Sul', 563323);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Sul', 2, 'País 68 América do Sul', 763029);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Sul', 2, 'País 69 América do Sul', 112653);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Sul', 1, 'País 70 América do Sul', 422037);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Sul', 3, 'País 71 América do Sul', 792406);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Sul', 1, 'País 72 América do Sul', 189574);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Sul', 1, 'País 73 América do Sul', 292617);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Sul', 3, 'País 74 América do Sul', 701963);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Sul', 1, 'País 75 América do Sul', 638483);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Sul', 3, 'País 76 América do Sul', 149710);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Sul', 2, 'País 77 América do Sul', 398234);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Sul', 1, 'País 78 América do Sul', 588177);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Sul', 2, 'País 79 América do Sul', 721283);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Sul', 3, 'País 80 América do Sul', 596342);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Sul', 3, 'País 81 América do Sul', 789689);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Sul', 1, 'País 82 América do Sul', 626410);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Sul', 2, 'País 83 América do Sul', 229824);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Sul', 3, 'País 84 América do Sul', 897082);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Sul', 2, 'País 85 América do Sul', 115578);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Sul', 1, 'País 86 América do Sul', 457992);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Sul', 3, 'País 87 América do Sul', 785609);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Sul', 3, 'País 88 América do Sul', 501972);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Sul', 2, 'País 89 América do Sul', 599380);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Sul', 2, 'País 90 América do Sul', 253252);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Sul', 1, 'País 91 América do Sul', 995407);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Sul', 2, 'País 92 América do Sul', 231902);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Sul', 2, 'País 93 América do Sul', 289209);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Sul', 3, 'País 94 América do Sul', 283534);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Sul', 1, 'País 95 América do Sul', 740369);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Sul', 1, 'País 96 América do Sul', 495109);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Sul', 3, 'País 97 América do Sul', 225739);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Sul', 3, 'País 98 América do Sul', 680367);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Sul', 2, 'País 99 América do Sul', 468314);
INSERT INTO countries (region, key_word, name, population) VALUES ('América do Sul', 3, 'País 100 América do Sul', 842661);
